[package]
version = "0.1.0"
name="make-a-book"
authors=["Michał Lipiński michal.lipinski@gmail.com"]
homepage=""
repository=""
description=""
edition="2024"
rust-version="1.88"
license="GPL-3"

[dependencies]
html2md = "0.2.15"

[lints]
workspace = true
